"""add cascade behavior to asset and chunks

Revision ID: 812baaee8fb0
Revises: d3a8d38d5854
Create Date: 2025-12-18 13:36:42.141790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812baaee8fb0'
down_revision: Union[str, None] = 'd3a8d38d5854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_asset_project_id_fkey', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'projects', ['asset_project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint('chunks_chunk_asset_id_fkey', 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key('chunks_chunk_asset_id_fkey', 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'])
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('assets_asset_project_id_fkey', 'assets', 'projects', ['asset_project_id'], ['project_id'])
    # ### end Alembic commands ###
